### ISSUE TITLE
Update dev_server console message to direct to the ddc_bundle.html file

### ISSUE THREAD

**Issue by nshahan** [dart-lang/rules_dart#37]
The message that is printed to the console: `Server running on localhost:8080` should also include information about how the html entry point has been rewritten and provide dev url.

**Comment by jakemac53** [comment]
This means forwarding some info from the dart_ddc_bundle rule to the dev_server rule. This could be done via a [provider](https://bazel.io/versions/master/docs/skylark/lib/skylark-provider.html), but since the dev_server rule is just a [macro](https://www.bazel.io/versions/master/docs/skylark/macros.html) it doesn't have access to those providers (its just a wrapper around dart_vm_binary).

Because of that I don't see a quick path to supporting this, other than making users hardcode the path to the bundled html file in their dev_server rule or something :(.

**Comment by jakemac53** [comment]
Ok I think we can effectively fix this in a similar way to https://github.com/dart-lang/rules_dart/issues/44, in addition to some changes to bazelify.

Essentially, we can add a `uri-substitution` argument to the server, which is by some new middleware to modify all request uris via `replaceFirst`. For this case we would provide a substitution from `web/{bundle}` to `web/${original}`. For the packages dir case we would provide a substitution value for each package, from `packages/${packageName}` to the actual path relative to `$RUNFILES/$WORKSPACE_NAME` (where the server serves from).

**Comment by jakemac53** [comment]
This is resolved now I think, you can just load the original input url path and it will actually load the ddc output html.
