### ISSUE TITLE
Support reading non-dart files from deps, even when using analyzer summaries

### ISSUE THREAD

**Issue by natebosch** [dart-lang/rules_dart#98]
Currently in order to read anything other than .dart files we require an aspect - this won't translate well to `dazel`.

We should add a `read_extensions_from_deps` (open to naming suggestions) on `dart_codegen_binary` and in the codegen action, gather up sources that end with this extension as extra inputs.

**Comment by natebosch** [comment]
@jakemac53 Any opinion on this? It's a pretty easy change to put together if you don't think it'll add performance issues.

**Comment by jakemac53** [comment]
I do think it can be implemented efficiently enough, we could even autogenerate aspects based on the config. Alternatively we could add a dict of extensions to transitive files to the dart provider. Either should be fine.

**Comment by natebosch** [comment]
I think we only need the aspect if we want to read files beyond our immediate deps? If we only want to handle first-level deps we can do `[f for f in ctx.files.deps if f.path.endswith(extension)]` and it should be fast enough.

**Comment by jakemac53** [comment]
I think it's important to support getting files from all transitive deps, although it would be good to also support only immediate deps as well.

Using nested sets from providers is really the only way to go long term for this, even for the direct deps case you really don't want to be iterating all the files from all your direct deps for each package if you can avoid it.

**Comment by jakemac53** [comment]
Take angular as an example, today it only needs generated files from immediate deps (and the aspect internally does just this). If it didn't do that using an aspect then every package that depends on angular would have to iterate all of angulars srcs. Note that this ends up happening for all transitive deps of yours, not just your package (since they also do codegen). You could easily get into a situation where you are iterating all of angulars srcs dozens of times during analysis, or conceivably even over a hundred times for a large app that uses material widgets and other shared widgets. That is just for angular itself, although core packages like this would admittedly be the worst offenders.

**Comment by natebosch** [comment]
It looks like it's possible to provide a utility method to create the aspects. They must be top-level as a restriction in skylark - so we can't do this entirely within `dart_codegen_rule`, but we can give an api that looks about like this: (will end up being hidden by build.yaml)

```
my_codegen_aspect = dart_codegen_aspect("my_codegen_aspect", [".exension.needed"])

my_codegen_rule = dart_codegen_rule(
    aspect = my_codegen_aspect,
    input_provider = "my_codegen_aspect",
    codegen_binary = ...
)
```
